#let 学校 = "中山大学"
#let 论文名称 = 学校 + "博士学位论文"
#let 论文中文题目 = "基于 typst 的\n学位论文模板"
#let 论文英文题目 = "A thesis template\nbased on typst"
#let 日期 = "二零二三年六月"
#let 中文页眉 = "基于 typst 的学位论文模板"

#let 中文作者名 = "张三"
#let 英文作者名 = "Zhang San"
#let 学号 = "1234567890"
#let 学院 = "某学院"
#let 专业 = "某专业"
#let 英文专业 = "Some Major"
#let 方向 = "某研究方向"
#let 中文导师名 = "李四"
#let 英文导师名 = "Li Si"
